coin:
  type: btc
flash:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverclassname: com.mysql.jdbc.Driver
    url: jdbc:mysql://AP_FLASH_MYSQL:3306/flash?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=utf8&useCompress=true
    username: FLASH_USER
    password: FLASH_PASS
    maximum-pool-size: 10


kafka:
  topic: ${coin.type}-share
  stream-config:
    bootstrap.servers: AP_BOOTSTRAP_SERVERS
    group.id: stream
    client.id: stream-client
    application.id: stream-app
    replication.factor: 3
    windowstore.changelog.additional.retention.ms: 86400000 #1day
    num.stream.threads: 3
    commit.interval.ms: 1000
    processing.guarantee: exactly_once
    state.cleanup.delay.ms: 6000000
    state.dir: data

  consumers:
      user:
        min5:
          topic: ${coin.type}-user-share-min5
        min15:
          topic: ${coin.type}-user-share-min15
        hour:
          topic: ${coin.type}-user-share-hour

management:
  endpoints:
    beans: # disable beans endpoint
      enabled: false
    web:
      exposure:
        include: health,info,env,metrics,prometheus
      base-path: /
